#ifndef	_WIFI_CONFIG_H_
#define	_WIFI_CONFIG_H_

#define	CONFIG_NRF700X_STA_MODE					y
#define	CONFIG_NRF700X_DATA_TX					y
#define	CONFIG_NRF700X_TCP_IP_CHECKSUM_OFFLOAD			y
#define	CONFIG_NRF700X_REG_DOMAIN				"00"
#define	CONFIG_NRF700X_LOG_VERBOSE				y
#define	CONFIG_NRF700X_WORKQ_STACK_SIZE				4096
#define	CONFIG_NRF700X_WORKQ_MAX_ITEMS				100
#define	CONFIG_NRF700X_MAX_TX_PENDING_QLEN			18
#define	CONFIG_NRF700X_QSPI_LOW_POWER				y
#define	CONFIG_NRF700X_PCB_LOSS_2G				0
#define	CONFIG_NRF700X_PCB_LOSS_5G_BAND1			0
#define	CONFIG_NRF700X_PCB_LOSS_5G_BAND2			0
#define	CONFIG_NRF700X_PCB_LOSS_5G_BAND3			0
#define	CONFIG_NRF700X_ANT_GAIN_2G				0
#define	CONFIG_NRF700X_ANT_GAIN_5G_BAND1			0
#define	CONFIG_NRF700X_ANT_GAIN_5G_BAND2			0
#define	CONFIG_NRF700X_ANT_GAIN_5G_BAND3			0
#define	CONFIG_NRF700X_BAND_2G_LOWER_EDGE_BACKOFF_DSSS		0
#define	CONFIG_NRF700X_BAND_2G_LOWER_EDGE_BACKOFF_HT		0
#define	CONFIG_NRF700X_BAND_2G_LOWER_EDGE_BACKOFF_HE		0
#define	CONFIG_NRF700X_BAND_2G_UPPER_EDGE_BACKOFF_DSSS		0
#define	CONFIG_NRF700X_BAND_2G_UPPER_EDGE_BACKOFF_HT		0
#define	CONFIG_NRF700X_BAND_2G_UPPER_EDGE_BACKOFF_HE		0
#define	CONFIG_NRF700X_BAND_UNII_1_LOWER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_1_LOWER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_1_UPPER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_1_UPPER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_2A_LOWER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_2A_LOWER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_2A_UPPER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_2A_UPPER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_2C_LOWER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_2C_LOWER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_2C_UPPER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_2C_UPPER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_3_LOWER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_3_LOWER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_3_UPPER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_3_UPPER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_4_LOWER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_4_LOWER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_BAND_UNII_4_UPPER_EDGE_BACKOFF_HT	0
#define	CONFIG_NRF700X_BAND_UNII_4_UPPER_EDGE_BACKOFF_HE	0
#define	CONFIG_NRF700X_RX_NUM_BUFS				48
#define	CONFIG_NRF700X_MAX_TX_AGGREGATION			12
#define	CONFIG_NRF700X_MAX_TX_TOKENS				10
#define	CONFIG_NRF700X_TX_MAX_DATA_SIZE				1600
#define	CONFIG_NRF700X_RX_MAX_DATA_SIZE				1600
#define	CONFIG_NRF700X_IRQ_WQ_PRIORITY				-15
#define	CONFIG_NRF700X_BH_WQ_PRIORITY				0
#define	CONFIG_NRF700X_IRQ_WQ_STACK_SIZE			2048
#define	CONFIG_NRF700X_BH_WQ_STACK_SIZE				2048
#define	CONFIG_NRF700X_TX_DONE_WQ_PRIORITY			0
#define	CONFIG_NRF700X_TX_DONE_WQ_STACK_SIZE			2048
#define	CONFIG_NRF700X_RX_WQ_PRIORITY				0
#define	CONFIG_NRF700X_RX_WQ_STACK_SIZE				2048
#define	CONFIG_NRF700X_RPU_PS_IDLE_TIMEOUT_MS			10
#define	CONFIG_NRF700X_RSSI_STALE_TIMEOUT_MS			1000

#define	CONFIG_WIFI_NRF700X_LOG_LEVEL				1
#define	CONFIG_NRF_WIFI_AP_DEAD_DETECT_TIMEOUT			20
#define	CONFIG_NRF700X_REG_DOMAIN				"00"
#define	CONFIG_NRF_WIFI_IFACE_MTU				1500

#endif /* !_WIFI_CONFIG_H_ */
