#ifndef	_WIFI_CONFIG_H_
#define	_WIFI_CONFIG_H_

#define	NRF_WIFI_RPU_RECOVERY
#define	NRF_WIFI_AP_DEAD_DETECT_TIMEOUT			20
#define	NRF_WIFI_IFACE_MTU				1500
#define	NRF70_STA_MODE
#define	NRF70_DATA_TX
#define	NRF70_UTIL
#define	NRF70_TCP_IP_CHECKSUM_OFFLOAD
#define	NRF70_RPU_EXTEND_TWT_SP
#define	NRF70_LOG_VERBOSE
#define	NRF_WIFI_MGMT_BUFF_OFFLOAD
#define	NRF_WIFI_FEAT_KEEPALIVE
#define	NRF_WIFI_KEEPALIVE_PERIOD_S			60
#define	NRF70_RX_NUM_BUFS				48
#define	NRF70_MAX_TX_TOKENS				10
#define	NRF70_RX_MAX_DATA_SIZE				1600
#define	NRF70_MAX_TX_PENDING_QLEN			18
#define	NRF70_RPU_PS_IDLE_TIMEOUT_MS			10
#define	NRF70_BAND_2G_LOWER_EDGE_BACKOFF_DSSS		0
#define	NRF70_BAND_2G_LOWER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_2G_LOWER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_2G_UPPER_EDGE_BACKOFF_DSSS		0
#define	NRF70_BAND_2G_UPPER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_2G_UPPER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_1_LOWER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_1_LOWER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_1_UPPER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_1_UPPER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_2A_LOWER_EDGE_BACKOFF_HT	0
#define	NRF70_BAND_UNII_2A_LOWER_EDGE_BACKOFF_HE	0
#define	NRF70_BAND_UNII_2A_UPPER_EDGE_BACKOFF_HT	0
#define	NRF70_BAND_UNII_2A_UPPER_EDGE_BACKOFF_HE	0
#define	NRF70_BAND_UNII_2C_LOWER_EDGE_BACKOFF_HT	0
#define	NRF70_BAND_UNII_2C_LOWER_EDGE_BACKOFF_HE	0
#define	NRF70_BAND_UNII_2C_UPPER_EDGE_BACKOFF_HT	0
#define	NRF70_BAND_UNII_2C_UPPER_EDGE_BACKOFF_HE	0
#define	NRF70_BAND_UNII_3_LOWER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_3_LOWER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_3_UPPER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_3_UPPER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_4_LOWER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_4_LOWER_EDGE_BACKOFF_HE		0
#define	NRF70_BAND_UNII_4_UPPER_EDGE_BACKOFF_HT		0
#define	NRF70_BAND_UNII_4_UPPER_EDGE_BACKOFF_HE		0
#define	NRF70_PCB_LOSS_2G				0
#define	NRF70_PCB_LOSS_5G_BAND1				0
#define	NRF70_PCB_LOSS_5G_BAND2				0
#define	NRF70_PCB_LOSS_5G_BAND3				0
#define	NRF70_ANT_GAIN_2G				0
#define	NRF70_ANT_GAIN_5G_BAND1				0
#define	NRF70_ANT_GAIN_5G_BAND2				0
#define	NRF70_ANT_GAIN_5G_BAND3				0
#define	NRF_WIFI_PS_INT_PS
#define	NRF_WIFI_RPU_RECOVERY_PS_ACTIVE_TIMEOUT_MS	50000
#define	NRF_WIFI_DISPLAY_SCAN_BSS_LIMIT			150
#define	NRF_WIFI_RPU_MIN_TIME_TO_ENTER_SLEEP_MS		1000
#define	WIFI_NRF70_LOG_LEVEL				1
#define	NRF_WIFI_MAX_PS_POLL_FAIL_CNT			3
#define	NRF70_SYSTEM_MODE

#endif /* !_WIFI_CONFIG_H_ */
